services:
  e2e-tests-shopware-6.5:
    build:
      context: .
      dockerfile: docker/e2e-tests/Dockerfile
      args:
        SHOPWARE_VERSION: 6.5.8.16
    environment:
      PHP_VERSION: 8.2
      XDEBUG_ENABLED: 1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./tests/E2E/Plugin:/var/www/html/custom/plugins/TestPlugin"
      - "./:/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration"
      # exclude by using anonymous volumes
      - "/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/tests/"
      - "/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/vendor/"

  e2e-tests-shopware-6.6:
    build:
      context: .
      dockerfile: docker/e2e-tests/Dockerfile
      args:
        SHOPWARE_VERSION: 6.6.9.0
    environment:
      PHP_VERSION: 8.3
      XDEBUG_ENABLED: 1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "./tests/E2E/Plugin:/var/www/html/custom/plugins/TestPlugin"
      - "./:/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration"
      # exclude by using anonymous volumes
      - "/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/tests/"
      - "/var/www/html/custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/vendor/"