name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  e2e-tests:
    name: E2E tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        shopware-version: [ 'v6.5.8.15', 'v6.5.8.16' ]
      fail-fast: false

    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: ${{ matrix.shopware-version }}
          php-version: 8.2
          mysql-version: "mariadb:10.11"
          install: true

      - name: Checkout code for test plugin
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./custom/plugins/TestPlugin

      - name: Replace repository files with test plugin files
        run: |
          mv ./custom/plugins/TestPlugin/tests/E2E/Plugin ./custom/plugins/TestPlugin_tmp && \
          rm -rf ./custom/plugins/TestPlugin && \
          mv ./custom/plugins/TestPlugin_tmp ./custom/plugins/TestPlugin

      - name: Checkout code for package
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration

      - name: Remove unnecessary package files
        run: |
          rm -rf ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/tests \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/.git \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/.github \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/.gitignore \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/LICENSE \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/README.md \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/captainhook.json \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/ecs.php \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/phpstan.baseline.neon \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/phpstan.neon.dist \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/phpunit.xml.dist \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/rector.php \
          ./custom/plugins/TestPlugin/packages/itb-shopware-code-based-plugin-configuration/renovate.json

      - name: Install package
        run: composer require it-bens/shopware-code-based-plugin-configuration

      - name: Run E2E tests
        working-directory: ./custom/plugins/TestPlugin
        run: |
          composer dump-autoload --dev
          php -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~' \
            ${GITHUB_WORKSPACE}/vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --log-junit ${GITHUB_WORKSPACE}/phpunit.junit.xml \
            --coverage-cobertura ${GITHUB_WORKSPACE}/cobertura.xml \
            --coverage-text