name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  code-style:
    name: Code style
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.3']
      fail-fast: false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run ECS
        run: ./vendor/bin/ecs --config=ecs.php check src tests

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.3']
      fail-fast: false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --configuration phpstan.neon

  unit-tests:
    name: Unit tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0da7aa657d958d32c117fc47e1f977e7524753c7 # v5.3.0
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}